//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseRegistrations = new HashSet<CourseRegistration>();
        }
    
        public int CourseId { get; set; }
        [Required]
        [RegularExpression(@"(^[a-zA-Z]{2}[\d]{4})$", ErrorMessage = "format should be XXYYYY, where X is alphabet and Y is number")]
        public string CourseCode { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "must start with alphabets")]
        public string CourseName { get; set; }
        [Required]
        [RegularExpression("(^[1-3])$", ErrorMessage = "range should be 1 to 3")]
        public Nullable<int> CreditHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
    }
}
