//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.CourseRegistrations = new HashSet<CourseRegistration>();
        }
    
        public int StudentId { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "must start with alphabets")]
        public string StudentName { get; set; }
        [Required]
        [RegularExpression(@"(^[a-zA-Z]{3}[\d]{6})$", ErrorMessage = "format should be XXXYYYYYY, where X is alphabet and Y is number")]
        public string StudentRegNo { get; set; }
        [Required]
        [RegularExpression("(^[1-9]|1[0-6])$", ErrorMessage = "range should be 1 to 16")]
        public Nullable<int> StudentSemester { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
    }
}
